In [2]:
import numpy as np

In [3]:
#1
vector = np.arange(1,11)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#2
matrix = np.zeros((3,3),dtype = int)
matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
#3
matrix = np.random.randint(1,11, size=(5,5))
matrix

array([[ 7,  6,  5, 10,  9],
       [10,  7,  6,  9,  9],
       [10,  6,  4,  6,  9],
       [ 4,  8,  2,  6,  6],
       [ 3,  7,  9,  7,  4]])

In [10]:
#4
matrix = np.random.random((4,4))
matrix

array([[0.27386727, 0.45747178, 0.44866095, 0.46524378],
       [0.3952525 , 0.40159293, 0.35182736, 0.81535982],
       [0.3851422 , 0.84312386, 0.44705041, 0.3513008 ],
       [0.60257623, 0.6633185 , 0.34650015, 0.92956676]])

In [20]:
#5
vector_a = np.random.randint(1,11, size=5)
vector_b = np.random.randint(1,11, size=5)
vector_a , vector_b

(array([4, 7, 3, 5, 8]), array([7, 3, 7, 3, 2]))

In [21]:
vector_a - vector_b

array([-3,  4, -4,  2,  6])

In [22]:
vector_a + vector_b

array([11, 10, 10,  8, 10])

In [23]:
vector_a * vector_b

array([28, 21, 21, 15, 16])

In [24]:
#6
vector_1 = np.random.randint(1,11, size=7)
vector_2 = np.random.randint(1,11, size=7)
vector_1, vector_2

(array([ 6,  1, 10,  5,  1,  4,  8]), array([ 7, 10, 10,  7,  7,  5,  6]))

In [25]:
np.dot(vector_1,vector_2)

262

In [26]:
#7
matrix_a = np.random.randint(1,11, size=(2,2))
matrix_b = np.random.randint(1,11, size=(2,3))
matrix_a , matrix_b

(array([[6, 8],
        [3, 8]]),
 array([[6, 7, 5],
        [7, 3, 1]]))

In [27]:
np.dot(matrix_a, matrix_b)

array([[92, 66, 38],
       [74, 45, 23]])

In [29]:
#8
matrix = np.random.randint(1,11, size=(3,3))
matrix

array([[3, 3, 6],
       [1, 9, 2],
       [6, 4, 1]])

In [30]:
inv_matrix = np.linalg.inv(matrix)
inv_matrix

array([[-0.00378788, -0.07954545,  0.18181818],
       [-0.04166667,  0.125     ,  0.        ],
       [ 0.18939394, -0.02272727, -0.09090909]])

In [31]:
#9
matrix = np.random.random((4,4))
matrix

array([[0.63510424, 0.35853563, 0.70550973, 0.91501093],
       [0.09927911, 0.38922499, 0.82669607, 0.9780618 ],
       [0.24816679, 0.09243703, 0.38991088, 0.39818096],
       [0.06508799, 0.64393761, 0.99543222, 0.2563396 ]])

In [32]:
matrix_T = matrix.T
matrix_T

array([[0.63510424, 0.09927911, 0.24816679, 0.06508799],
       [0.35853563, 0.38922499, 0.09243703, 0.64393761],
       [0.70550973, 0.82669607, 0.38991088, 0.99543222],
       [0.91501093, 0.9780618 , 0.39818096, 0.2563396 ]])

In [33]:
#10
matrix = np.random.randint(1,11, size=(3,4))
vector = np.random.randint(1,11, size=4)
np.dot(matrix, vector)

array([ 36, 126,  85])

In [35]:
#11
matrix = np.random.random((2,3))
vector = np.random.random(3)
matrix, vector

(array([[0.52395584, 0.36220824, 0.8669961 ],
        [0.95659754, 0.20681451, 0.86993715]]),
 array([0.82843229, 0.67045136, 0.53133708]))

In [36]:
np.dot(matrix, vector)

array([1.13757211, 1.39336523])

In [37]:
#12
matrix_a = np.random.randint(1,11, size=(2,2))
matrix_b = np.random.randint(1,11, size=(2,2))
matrix_a, matrix_b

(array([[1, 5],
        [1, 5]]),
 array([[5, 6],
        [4, 2]]))

In [38]:
matrix_a * matrix_b

array([[ 5, 30],
       [ 4, 10]])

In [39]:
#13
matrix_a = np.random.randint(1,11, size=(2,2))
matrix_b = np.random.randint(1,11, size=(2,2))
matrix_a, matrix_b

(array([[7, 4],
        [6, 5]]),
 array([[ 6, 10],
        [ 7,  4]]))

In [40]:
np.dot(matrix_a,matrix_b)

array([[70, 86],
       [71, 80]])

In [41]:
#14
matrix = np.random.randint(1,101, size=(5,5))
matrix, np.sum(matrix)

(array([[ 27,  69,  66,   7,  13],
        [100,  24,  33,  38,  93],
        [ 49,  95,  92,  54,  89],
        [ 10,  63,  98,  62,  13],
        [ 99,  66,  64,  17,  73]]),
 1414)

In [43]:
#15
matrix_a = np.random.randint(1,11, size=(4,4))
matrix_b = np.random.randint(1,11, size=(4,4))
matrix_a, matrix_b

(array([[ 8,  2,  6,  1],
        [ 7,  1,  5,  8],
        [10,  3,  2,  2],
        [ 7,  2,  9,  7]]),
 array([[ 4,  5,  7,  8],
        [ 6,  6,  4, 10],
        [ 2,  7,  6,  4],
        [10,  8,  3,  5]]))

In [44]:
matrix_a - matrix_b

array([[ 4, -3, -1, -7],
       [ 1, -5,  1, -2],
       [ 8, -4, -4, -2],
       [-3, -6,  6,  2]])

In [46]:
#16
matrix = np.random.random((3,3))
matrix

array([[0.4009832 , 0.70829324, 0.93931003],
       [0.2097455 , 0.32600343, 0.58346924],
       [0.53200871, 0.59283589, 0.29338253]])

In [49]:
a = matrix[0][0]+matrix[0][1]+matrix[0][2]
b = matrix[1][0]+matrix[1][1]+matrix[1][2]
c = matrix[2][0]+matrix[2][1]+matrix[2][2]
vector = np.array([a,b,c])
vector

array([2.04858647, 1.11921816, 1.41822712])

In [52]:
#17
matrix = np.random.randint(1,11, size=(3,4))
matrix , matrix**2

(array([[ 2,  3,  5,  3],
        [ 7,  7,  7,  5],
        [ 3,  6,  4, 10]]),
 array([[  4,   9,  25,   9],
        [ 49,  49,  49,  25],
        [  9,  36,  16, 100]]))

In [53]:
#18
vector = np.random.randint(1,51, size=4)
vector

array([48, 32, 14, 17])

In [54]:
vector_x = vector**0.5
vector_x

array([6.92820323, 5.65685425, 3.74165739, 4.12310563])